backend:
  name: github
  repo: your-username/your-repo-name   # ðŸ‘ˆ yahan apna GitHub repo likhna hai
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "public/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "description", label: "Short Description", widget: "string" }
      - { name: "cover", label: "Cover Image", widget: "image", required: false }
      - { name: "body", label: "Post Content", widget: "markdown" }
